### ISSUE TITLE
The --web option is hitting a ruby error 

### ISSUE THREAD

**Issue by orta** [CocoaPods/cocoapods-search#24]
It looks like the `open!` func doesn't exist anymore according to https://github.com/CocoaPods/CocoaPods/issues/7702

```sh
NoMethodError - undefined method `open!' for #<Pod::Command::Search:0x007f94f58ad180>
Did you mean?  open
/Library/Ruby/Gems/2.3.0/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:79:in `web_search'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:61:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

I'm not actually sure where that comes from, after a quick look

**Comment by dnkoutso** [comment]
fixed by https://github.com/CocoaPods/cocoapods-search/pull/26 actually.
